'use client';
import {useEffect,useMemo,useState} from 'react';
import type {Entry,ItemState,Library,Period,Reading,Source} from '@/lib/types';
import {AccountBar,DraftBanner,ItemActions} from './account';
import PoSExperiment from './pos-experiment';
import SkillGuide from './skill-guide';
import StudyRecord,{studyLabel} from './study-record';
const periods:Record<Period,string>={daily:'日榜',weekly:'周榜',monthly:'月榜'};
const number=(n?:number)=>new Intl.NumberFormat('en-US').format(n||0);
const time=(s:string)=>new Intl.DateTimeFormat('zh-CN',{timeZone:'America/New_York',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s));
function Icon({kind='star'}:{kind?:string}){return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true">{kind==='star'?<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3l-5.6 2.9 1.1-6.2L3 9.6l6.2-.9Z"/>:kind==='fork'?<><path d="M6 6v4c0 3 12 1 12 5v3M12 12v6"/><circle cx="6" cy="4" r="2"/><circle cx="18" cy="4" r="2"/><path d="M18 6v3"/><circle cx="12" cy="20" r="2"/></>:kind==='refresh'?<path d="M20 11a8 8 0 1 0-2 6M20 4v7h-7"/>:kind==='book'?<path d="M3 4h7l2 2 2-2h7v16h-7l-2 1-2-1H3ZM12 6v15"/>:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>}</svg>}
function best(all:Reading[],id:string,hash?:string,deep=false){return all.find(r=>r.itemId===id&&(!hash||r.sourceHash===hash)&&(deep?r.level==='deep':r.level==='brief'))||(!deep?all.find(r=>r.itemId===id&&(!hash||r.sourceHash===hash)&&r.level==='translation'):undefined);}
const paperByline=(e:Entry,r?:Reading)=>r?.attribution?.label||e.attribution?.label||((e.authors?.slice(0,2).join(' · ')||'作者信息待核查')+((e.authors?.length||0)>2?' 等':''));
const pathFor=(e:Entry)=>`#/read/${encodeURIComponent(e.id)}`;
export default function Reader(){
 const [data,setData]=useState<Library|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [states,setStates]=useState<Record<string,ItemState>>({});
 async function load(){try{const r=await fetch('/api/library');const d=await r.json() as Library & {error?:string};if(!r.ok)throw Error(d.error);setData(d);if(d.viewer?.signedIn){const s=await fetch('/api/me/state');if(s.ok)setStates(((await s.json()) as {states:Record<string,ItemState>}).states);}}catch(e){setError((e as Error).message);}}
 const [route,setRoute]=useState(''),[query,setQuery]=useState(''),[focus,setFocus]=useState(false),[font,setFont]=useState(18);
 useEffect(()=>{const change=()=>{setRoute(location.hash||'#/github/daily');window.scrollTo(0,0);};change();window.addEventListener('hashchange',change);load();return()=>window.removeEventListener('hashchange',change);},[]);
 const [,section='github',key='daily']=route.split('/');const source:Source=section==='hf'?'hf':'github';const period:Period=key in periods?key as Period:'daily';
 const itemId=section==='read'?decodeURIComponent(key):'';const board=data?.boards.find(b=>b.source===source&&b.period===period);
 const entries=useMemo(()=>Array.from(new Map([...(data?.readings||[]).flatMap(r=>r.entry?[r.entry]:[]),...(data?.boards||[]).flatMap(b=>b.items)].map(e=>[e.id,e])).values()),[data]);
 const item=entries.find(e=>e.id===itemId);const readings=data?.readings||[];
 const deep=readings.filter((r,i,a)=>r.level==='deep'&&a.findIndex(x=>x.itemId===r.itemId&&x.level==='deep')===i);
 const guides=readings.filter((r,i,a)=>r.format==='skill_guide'&&a.findIndex(x=>x.itemId===r.itemId&&x.format==='skill_guide')===i);
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());
 const recommendations=readings.filter((r,i,a)=>r.level==='brief'&&r.sections.some(s=>s.heading==='精读推荐')&&new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date(r.generatedAt))===today&&a.findIndex(x=>x.itemId===r.itemId&&x.level==='brief')===i).slice(0,2);
 const reading=item?best(readings,item.id,item.sourceHash,true)||best(readings,item.id,undefined,true)||best(readings,item.id,item.sourceHash):undefined;
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/refresh',{method:'POST'});const d=await r.json() as Library & {error?:string};if(!r.ok)throw Error(d.error);setData(old=>({...d,viewer:old?.viewer}));}catch(e){setError(e instanceof Error?e.message:'刷新失败');}finally{setBusy(false);}}
 const boardEntries=source==='hf'?(board?.items||[]).slice(0,5):(board?.items||[]);
 const filtered=boardEntries.filter(e=>`${e.title} ${e.summary} ${best(readings,e.id,e.sourceHash)?.title||''} ${e.language||''}`.toLowerCase().includes(query.toLowerCase()));
 return <div className={focus?'site focus':'site'}><a className="skip" href="#main">跳到正文</a>
  <header className="masthead"><a href="#/github/daily" className="wordmark">JARVIS<span>.</span></a><div className="masthead-sub"><span>开源与论文阅读台</span><small>发现 · 理解 · 动手</small></div><div className="masthead-actions"><span className="edition">阅读实验室 / 01</span><AccountBar viewer={data?.viewer}/><button className="refresh" onClick={refresh} disabled={busy}><Icon kind="refresh"/>{busy?'正在同步六榜':'刷新最新内容'}</button></div></header>
  <nav className="main-nav" aria-label="主导航"><div><a className={section==='github'?'active':''} href="#/github/daily">GitHub 项目<span>01</span></a><a className={section==='hf'?'active':''} href="#/hf/daily">HF 论文<span>02</span></a><a className={section==='deep'?'active':''} href="#/deep">精读书架<span>03</span></a></div><span className="nav-caption">从热度出发，走到机制</span></nav>
  {(error||data?.notice)&&<div role="status" className="notice">{error||data?.notice}{error&&<button onClick={()=>data?refresh():location.reload()}>重试</button>}</div>}
  <main id="main" tabIndex={-1}>{!data&&!error?<div className="loading" aria-label="正在读取榜单">{[1,2,3,4].map(n=><div key={n} className="skeleton"/>)}</div>:section==='read'?item?<div className="article-layout">
   <article className="article" style={{'--reading-font':font+'px'} as React.CSSProperties}><a className="back" href={item.kind==='paper'?'#/hf/daily':'#/github/daily'}>返回{item.kind==='paper'?'论文':'项目'}榜单</a><div className="article-kicker">{item.kind==='paper'?'PAPER / 论文':'REPOSITORY / 项目'}<span>{reading?studyLabel(reading):'原文与中文介绍'}</span></div><h1>{reading?.title||item.title}</h1><p className="original-title">{item.title}</p>{item.kind==='paper'&&<p className="paper-attribution">{paperByline(item,reading)}{reading?.attribution&&<a href={reading.attribution.url} target="_blank" rel="noreferrer" title={reading.attribution.locator}> · 出处 ↗</a>}</p>}
    <div className="article-tools"><a href={item.url} target="_blank" rel="noreferrer">{item.kind==='paper'?'HF 原文':'GitHub 仓库'}</a>{item.pdfUrl&&<a href={item.pdfUrl} target="_blank" rel="noreferrer">论文 PDF</a>}{item.codeUrl&&<a href={item.codeUrl} target="_blank" rel="noreferrer">代码</a>}<ItemActions itemId={item.id} viewer={data?.viewer} state={states[item.id]} onChange={st=>setStates(o=>{const n={...o};if(st)n[item.id]=st;else delete n[item.id];return n;})}/><div>{reading&&<a href={`/api/readings/export?itemId=${encodeURIComponent(reading.itemId)}&version=${encodeURIComponent(reading.generatedAt)}&level=${reading.level}`} download>保存阅读笔记</a>}<button onClick={()=>setFont(n=>Math.max(16,n-1))} aria-label="缩小字体">A−</button><button onClick={()=>setFont(n=>Math.min(24,n+1))} aria-label="放大字体">A＋</button><button onClick={()=>setFocus(!focus)}>{focus?'退出专注':'专注阅读'}</button></div></div>
    {reading?<><DraftBanner reading={reading} viewer={data?.viewer} onPublished={load}/>{reading.sourceHash!==item.sourceHash&&<div className="notice">本篇保留写作时的来源版本；当前榜单描述已变化，请结合文中固定来源阅读。</div>}<p className="article-deck">{reading.coverage==='title_only'?'论文标题已翻译；中文摘要和深入解读尚待处理。完整原始摘要可在本文末尾展开。':reading.summary}</p><div className="byline">{reading.author} · {time(reading.generatedAt)}（美东） · {reading.format==='skill_guide'?'实际 Skill 定义与流程':reading.coverage==='source_code'?'实际代码证据':reading.coverage==='fulltext'?'论文正文证据':reading.coverage==='translation'?'原文翻译':reading.coverage==='title_only'?'仅标题翻译':'摘要或 README 证据'}</div>
     {reading.level==='brief'&&reading.format!=='skill_guide'&&<p className="scope-note">这是一篇摘要解读，用于判断是否值得精读。依据范围：{reading.coverage==='abstract'?'论文摘要':'README 或相关介绍'}；尚未完成源码或论文全文精读。</p>}<StudyRecord reading={reading}/>{reading.skillCards&&<SkillGuide cards={reading.skillCards}/>}
     {reading.sections.map((s,i)=><section id={'s'+i} key={i} className="reading-section"><div className="section-number">{String(i+1).padStart(2,'0')}</div><h2>{s.heading}</h2>{s.body.split(/\n\s*\n/).map((p,j)=><p key={j}>{p}</p>)}<div className="citations">{s.citations.map(c=>{const ref=reading.sources.find(x=>x.id===c);return ref?<a key={c} href={ref.url} target="_blank" rel="noreferrer">来源：{ref.locator||ref.title}</a>:null;})}</div></section>)}
     {!!reading.study?.connections.length&&<section className="connections"><h2>从这里继续想</h2>{reading.study.connections.map((c,i)=><div key={i}><h3>{c.title}</h3><p>{c.body}</p>{c.itemId&&<a href={`#/read/${encodeURIComponent(c.itemId)}`}>关联阅读 ↗</a>}</div>)}</section>}
     {item.id==='paper:2610.01415'&&reading.level==='deep'&&<PoSExperiment/>}{!!reading.terms?.length&&<section className="glossary"><h2>术语，拆开看</h2>{reading.terms.map(t=><details key={t.term}><summary>{t.term}</summary><p>{t.explanation}</p></details>)}</section>}{!!reading.limitations.length&&<section className="limits"><h2>也要记住边界</h2><ul>{reading.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></section>}</>:<div className="pending"><h2>这篇解读正在等待作者处理</h2><p>榜单已同步；精读需要核查实际源码或论文正文。分析导入后自动显示中文解读。</p></div>}
    <details className="source-text"><summary>查看完整原始{item.kind==='paper'?'摘要':'描述'}</summary><p>{item.summary||'来源没有提供描述。'}</p></details>
   </article><aside className="article-aside"><span className="eyebrow">阅读路标</span><nav aria-label="文章目录">{reading?.sections.map((s,i)=><a key={i} href={'#s'+i} onClick={e=>{e.preventDefault();document.getElementById('s'+i)?.scrollIntoView({behavior:'smooth'});}}><span>{String(i+1).padStart(2,'0')}</span>{s.heading}</a>)}</nav><div className="margin-note"><span className="eyebrow">原始信号</span><strong>{number(item.kind==='paper'?item.votes:item.stars)}</strong><span>{item.kind==='paper'?'HF 赞数':'GitHub Stars'}</span><p>热度帮助发现内容，不替代质量判断。类比帮助理解，不替代技术定义。</p></div></aside>
  </div>:<div className="empty"><h1>没有找到这个条目</h1><a href="#/github/daily">返回榜单</a></div>:section==='deep'?<div className="shelf"><div className="section-heading"><span className="eyebrow">THE READING ROOM</span><h1>把机制读透。</h1><p>能复述机制、讲清细节，形成自己的判断和关联。摘要与工具指南另行标注。</p></div>{deep.length?deep.map((r,i)=><a className="shelf-entry" key={r.itemId} href={`#/read/${encodeURIComponent(r.itemId)}`}><span className="large-number">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">{r.itemId.startsWith('paper:')?'论文':'开源项目'} · {studyLabel(r)}</span><h2>{r.title}</h2><p>{r.summary}</p><small>{r.sections.length} 个章节 · {r.generatedAt.slice(0,10)} · 持续沉淀</small></div><Icon kind="book"/></a>):<div className="empty"><p>精读还在准备，先从三榜发现值得了解的内容。</p></div>}{!!guides.length&&<><h2 className="guide-heading">工具与 Skill 选用指南</h2>{guides.map(r=><a className="shelf-entry" key={r.itemId} href={`#/read/${encodeURIComponent(r.itemId)}`}><Icon kind="book"/><div><span className="eyebrow">选用指南 · {r.skillCards?.length} 个 skill</span><h2>{r.title}</h2><p>{r.summary}</p></div></a>)}</>}</div>:
  <div className="board-layout"><section className="board-main"><div className="section-heading"><div className="eyebrow">{source==='github'?'OPEN SOURCE / 开源观察':'RESEARCH / 论文雷达'}</div><h1>{source==='github'?'好项目，从这里读起。':'新研究，从问题读起。'}</h1><p>{source==='github'?'保留 GitHub Trending 原始顺序，让发现不止于一颗 Star。':'日、周、月各取来源前 5 篇，保留原始顺序。精读推荐每天 0–2 篇。'}</p></div><div className="board-toolbar"><div className="period-tabs" aria-label="榜单周期">{Object.entries(periods).map(([p,label])=><a key={p} className={p===period?'selected':''} href={`#/${source}/${p}`}>{label}</a>)}</div><label className="search"><Icon kind="search"/><span className="sr-only">搜索当前榜单</span><input placeholder="搜索当前榜单" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
   {board&&<div className="board-meta"><span>{boardEntries.length} {source==='github'?'个项目':'篇论文'}<span className="meta-separator">/</span>来源日期 {board.sourceDate}</span><a href={board.url} target="_blank" rel="noreferrer">查看原始榜单</a></div>}{board?.stale&&<div className="notice">{board.error} · 当前展示上次成功内容。</div>}
   <div className="entries">{filtered.map(e=>{const r=readings.find(r=>r.itemId===e.id&&r.sourceHash===e.sourceHash&&r.level==='translation')||best(readings,e.id,e.sourceHash),d=best(readings,e.id,e.sourceHash,true);return <article className="entry" key={`${board?.id}:${e.rank}`}><span className="entry-rank">{String(e.rank).padStart(2,'0')}</span><div className="entry-content"><div className="entry-heading"><a href={pathFor(e)}>{source==='github'?<><span className="owner">{e.title.split('/')[0]} / </span><b>{e.title.split('/')[1]}</b></>:r?.title||e.title}</a>{source==='hf'&&<span className="paper-attribution">{paperByline(e,best(readings,e.id,e.sourceHash,true)||best(readings,e.id,e.sourceHash))}</span>}{d&&<span className="badge">{studyLabel(d)}</span>}{best(readings,e.id,e.sourceHash)?.format==='skill_guide'&&<span className="badge">Skill 选用指南</span>}</div>{r?.coverage!=='title_only'&&<p className="entry-description">{r?.summary||e.summary||'来源未提供描述。'}</p>}{r?.coverage==='title_only'&&<p className="paper-original">标题已翻译 · 原始摘要已同步{best(readings,e.id,e.sourceHash)?.level==='brief'?' · 有中文解读':' · 中文摘要待处理'}</p>}{!r&&<span className="translation-pending">中文介绍待处理 · 原文已同步</span>}
    <div className="entry-bottom"><div className="entry-stats">{e.language&&<span><i className="language-dot" style={{background:e.languageColor||'#677b70'}}/>{e.language}</span>}{source==='github'?<><span><Icon/>{number(e.stars)}</span><span><Icon kind="fork"/>{number(e.forks)}</span>{!!e.contributors?.length&&<span className="contributors"><span>贡献者</span>{e.contributors.map((c,i)=><a key={c.name+":"+i} href={c.url} target="_blank" rel="noreferrer" title={c.name}><img src={c.avatar} width="22" height="22" alt={c.name}/></a>)}</span>}</>:<><span><Icon/>{number(e.votes)} 赞</span><span>{e.published}</span><span>{e.authors?.slice(0,2).join(' · ')}{(e.authors?.length||0)>2?' 等':''}</span></>}</div><div className="entry-links">{source==='github'&&<span className="growth">+{number(e.growth)}<small>{period==='daily'?'今日':period==='weekly'?'本周':'本月'} Stars</small></span>}<a href={pathFor(e)} className="read-link">{d?'阅读精读':best(readings,e.id,e.sourceHash)?.format==='skill_guide'?'查找适用 skill':best(readings,e.id,e.sourceHash)?.level==='brief'?'阅读摘要解读':'打开阅读'}</a></div></div>
   </div></article>;})}</div>{!filtered.length&&<div className="empty"><p>{query?'没有匹配的条目，请尝试标题或编程语言。':'这个榜单还没有内容，请刷新或查看来源。'}</p></div>}
  </section><aside className="discovery-aside"><div className="aside-top"><span className="eyebrow">EDITOR’S DESK</span><h2>不只收藏，<br/>还要读懂。</h2><div className="aside-rule"/><p>每天发现很多，<br/>每次读透一点。</p></div>{recommendations.map(r=><a className="featured-reading" key={r.itemId} href={`#/read/${encodeURIComponent(r.itemId)}`}><span className="eyebrow">精读候选 / {r.itemId.startsWith('paper:')?'论文':'项目'}</span><h3>{r.title}</h3><p>{r.summary.slice(0,100)}</p><span className="feature-bottom"><Icon kind="book"/>进入阅读</span></a>)}{guides.slice(0,1).map(r=><a className="featured-reading" key={r.itemId} href={`#/read/${encodeURIComponent(r.itemId)}`}><span className="eyebrow">Skill 选用指南</span><h3>{r.title}</h3><p>{r.summary}</p></a>)}<div className="sync-note"><span className="eyebrow">来源与更新</span><p>{board?`最近同步 ${time(board.fetchedAt)}（美东）`:'尚未同步'}</p><p>日、周、月分别获取，跨榜保留重复。来源失败时保留上一份成功内容。</p><a href="/authoring.json" target="_blank" rel="noreferrer">中文分析与精读流程</a></div></aside></div>}</main>
  <footer><a href="#/github/daily">JARVIS.</a><span>原始事实 · 形象解释 · 可追溯判断</span><span>GitHub & Hugging Face · America/New_York</span></footer>
 </div>;
}
